name: face_cropper
description: A flutter package that detects face in an image and gives cropped image of face.
version: 0.0.2
repository: https://github.com/sagarRawatUK/face_cropper

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  google_mlkit_face_detection: ^0.9.0
  image: ^4.1.7
  logger: ^2.0.2+1
  path_provider: ^2.1.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter: null

# This package supports all platforms listed below.
platforms:
  android:
  ios: